# config.make generated by configure script
POCO_CONFIG = Linux
POCO_BASE = /home/kali/Documents/GitHub/poco-1.13.3
POCO_BUILD = /home/kali/Documents/GitHub/poco-1.13.3
POCO_FLAGS = 
POCO_LDFLAGS = 
POCO_PREFIX = /usr/local
OMIT = Data/ODBC Data/MySQL Data/PostgreSQL MongoDB Redis PDF CppParser
LINKMODE = STATIC
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_FLAGS
export POCO_LDFLAGS
export POCO_PREFIX
export LINKMODE
